apiVersion: v1
kind: Service
metadata:
  name: pg-psl
  labels:
    app: postgresql
spec:
  selector:
    app: postgresql
  ports:
    - protocol: TCP
      name: database
      port: 5432
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: es-psl
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
    - protocol: TCP
      name: database
      port: 9200
  type: LoadBalancer
