// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: generated.proto

package unicampus_api_admission_v1alpha1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type School struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *School) Reset()         { *m = School{} }
func (m *School) String() string { return proto.CompactTextString(m) }
func (*School) ProtoMessage()    {}
func (*School) Descriptor() ([]byte, []int) {
	return fileDescriptor_generated_20fa2873433b475f, []int{0}
}
func (m *School) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *School) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_School.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *School) XXX_Merge(src proto.Message) {
	xxx_messageInfo_School.Merge(dst, src)
}
func (m *School) XXX_Size() int {
	return m.Size()
}
func (m *School) XXX_DiscardUnknown() {
	xxx_messageInfo_School.DiscardUnknown(m)
}

var xxx_messageInfo_School proto.InternalMessageInfo

func (m *School) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *School) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *School) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Student struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Student) Reset()         { *m = Student{} }
func (m *Student) String() string { return proto.CompactTextString(m) }
func (*Student) ProtoMessage()    {}
func (*Student) Descriptor() ([]byte, []int) {
	return fileDescriptor_generated_20fa2873433b475f, []int{1}
}
func (m *Student) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Student) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Student.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *Student) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Student.Merge(dst, src)
}
func (m *Student) XXX_Size() int {
	return m.Size()
}
func (m *Student) XXX_DiscardUnknown() {
	xxx_messageInfo_Student.DiscardUnknown(m)
}

var xxx_messageInfo_Student proto.InternalMessageInfo

func (m *Student) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Student) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Student) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Student) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Application struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	School               *School  `protobuf:"bytes,2,opt,name=school" json:"school,omitempty"`
	Student              *Student `protobuf:"bytes,3,opt,name=student" json:"student,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Application) Reset()         { *m = Application{} }
func (m *Application) String() string { return proto.CompactTextString(m) }
func (*Application) ProtoMessage()    {}
func (*Application) Descriptor() ([]byte, []int) {
	return fileDescriptor_generated_20fa2873433b475f, []int{2}
}
func (m *Application) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Application) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Application.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *Application) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Application.Merge(dst, src)
}
func (m *Application) XXX_Size() int {
	return m.Size()
}
func (m *Application) XXX_DiscardUnknown() {
	xxx_messageInfo_Application.DiscardUnknown(m)
}

var xxx_messageInfo_Application proto.InternalMessageInfo

func (m *Application) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Application) GetSchool() *School {
	if m != nil {
		return m.School
	}
	return nil
}

func (m *Application) GetStudent() *Student {
	if m != nil {
		return m.Student
	}
	return nil
}

type Query struct {
	Query                string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Query) Reset()         { *m = Query{} }
func (m *Query) String() string { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()    {}
func (*Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_generated_20fa2873433b475f, []int{3}
}
func (m *Query) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Query.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Query.Merge(dst, src)
}
func (m *Query) XXX_Size() int {
	return m.Size()
}
func (m *Query) XXX_DiscardUnknown() {
	xxx_messageInfo_Query.DiscardUnknown(m)
}

var xxx_messageInfo_Query proto.InternalMessageInfo

func (m *Query) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type Critera struct {
	Sector               string   `protobuf:"bytes,1,opt,name=sector,proto3" json:"sector,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Critera) Reset()         { *m = Critera{} }
func (m *Critera) String() string { return proto.CompactTextString(m) }
func (*Critera) ProtoMessage()    {}
func (*Critera) Descriptor() ([]byte, []int) {
	return fileDescriptor_generated_20fa2873433b475f, []int{4}
}
func (m *Critera) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Critera) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Critera.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *Critera) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Critera.Merge(dst, src)
}
func (m *Critera) XXX_Size() int {
	return m.Size()
}
func (m *Critera) XXX_DiscardUnknown() {
	xxx_messageInfo_Critera.DiscardUnknown(m)
}

var xxx_messageInfo_Critera proto.InternalMessageInfo

func (m *Critera) GetSector() string {
	if m != nil {
		return m.Sector
	}
	return ""
}

type Offset struct {
	First                uint64   `protobuf:"varint,1,opt,name=first,proto3" json:"first,omitempty"`
	Offset               uint64   `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Offset) Reset()         { *m = Offset{} }
func (m *Offset) String() string { return proto.CompactTextString(m) }
func (*Offset) ProtoMessage()    {}
func (*Offset) Descriptor() ([]byte, []int) {
	return fileDescriptor_generated_20fa2873433b475f, []int{5}
}
func (m *Offset) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Offset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Offset.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *Offset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Offset.Merge(dst, src)
}
func (m *Offset) XXX_Size() int {
	return m.Size()
}
func (m *Offset) XXX_DiscardUnknown() {
	xxx_messageInfo_Offset.DiscardUnknown(m)
}

var xxx_messageInfo_Offset proto.InternalMessageInfo

func (m *Offset) GetFirst() uint64 {
	if m != nil {
		return m.First
	}
	return 0
}

func (m *Offset) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func init() {
	proto.RegisterType((*School)(nil), "unicampus.api.admission.v1.School")
	proto.RegisterType((*Student)(nil), "unicampus.api.admission.v1.Student")
	proto.RegisterType((*Application)(nil), "unicampus.api.admission.v1.Application")
	proto.RegisterType((*Query)(nil), "unicampus.api.admission.v1.Query")
	proto.RegisterType((*Critera)(nil), "unicampus.api.admission.v1.Critera")
	proto.RegisterType((*Offset)(nil), "unicampus.api.admission.v1.Offset")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AdmissionServiceClient is the client API for AdmissionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AdmissionServiceClient interface {
	ListSchools(ctx context.Context, opts ...grpc.CallOption) (AdmissionService_ListSchoolsClient, error)
	ListSchoolsByQuery(ctx context.Context, in *Query, opts ...grpc.CallOption) (AdmissionService_ListSchoolsByQueryClient, error)
	ListSchoolsByCritera(ctx context.Context, in *Critera, opts ...grpc.CallOption) (AdmissionService_ListSchoolsByCriteraClient, error)
	ListSchoolsByOffset(ctx context.Context, in *Offset, opts ...grpc.CallOption) (AdmissionService_ListSchoolsByOffsetClient, error)
	GetSchool(ctx context.Context, in *School, opts ...grpc.CallOption) (*School, error)
	PutSchool(ctx context.Context, in *School, opts ...grpc.CallOption) (*School, error)
	DeleteSchool(ctx context.Context, in *School, opts ...grpc.CallOption) (*School, error)
	AppyStudentToSchool(ctx context.Context, in *Application, opts ...grpc.CallOption) (*Application, error)
	GetStudent(ctx context.Context, in *Student, opts ...grpc.CallOption) (*Student, error)
	PutStudent(ctx context.Context, in *Student, opts ...grpc.CallOption) (*Student, error)
	DeleteStudent(ctx context.Context, in *Student, opts ...grpc.CallOption) (*Student, error)
}

type admissionServiceClient struct {
	cc *grpc.ClientConn
}

func NewAdmissionServiceClient(cc *grpc.ClientConn) AdmissionServiceClient {
	return &admissionServiceClient{cc}
}

func (c *admissionServiceClient) ListSchools(ctx context.Context, opts ...grpc.CallOption) (AdmissionService_ListSchoolsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AdmissionService_serviceDesc.Streams[0], "/unicampus.api.admission.v1.AdmissionService/ListSchools", opts...)
	if err != nil {
		return nil, err
	}
	x := &admissionServiceListSchoolsClient{stream}
	return x, nil
}

type AdmissionService_ListSchoolsClient interface {
	Send(*School) error
	Recv() (*School, error)
	grpc.ClientStream
}

type admissionServiceListSchoolsClient struct {
	grpc.ClientStream
}

func (x *admissionServiceListSchoolsClient) Send(m *School) error {
	return x.ClientStream.SendMsg(m)
}

func (x *admissionServiceListSchoolsClient) Recv() (*School, error) {
	m := new(School)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *admissionServiceClient) ListSchoolsByQuery(ctx context.Context, in *Query, opts ...grpc.CallOption) (AdmissionService_ListSchoolsByQueryClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AdmissionService_serviceDesc.Streams[1], "/unicampus.api.admission.v1.AdmissionService/ListSchoolsByQuery", opts...)
	if err != nil {
		return nil, err
	}
	x := &admissionServiceListSchoolsByQueryClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AdmissionService_ListSchoolsByQueryClient interface {
	Recv() (*School, error)
	grpc.ClientStream
}

type admissionServiceListSchoolsByQueryClient struct {
	grpc.ClientStream
}

func (x *admissionServiceListSchoolsByQueryClient) Recv() (*School, error) {
	m := new(School)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *admissionServiceClient) ListSchoolsByCritera(ctx context.Context, in *Critera, opts ...grpc.CallOption) (AdmissionService_ListSchoolsByCriteraClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AdmissionService_serviceDesc.Streams[2], "/unicampus.api.admission.v1.AdmissionService/ListSchoolsByCritera", opts...)
	if err != nil {
		return nil, err
	}
	x := &admissionServiceListSchoolsByCriteraClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AdmissionService_ListSchoolsByCriteraClient interface {
	Recv() (*School, error)
	grpc.ClientStream
}

type admissionServiceListSchoolsByCriteraClient struct {
	grpc.ClientStream
}

func (x *admissionServiceListSchoolsByCriteraClient) Recv() (*School, error) {
	m := new(School)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *admissionServiceClient) ListSchoolsByOffset(ctx context.Context, in *Offset, opts ...grpc.CallOption) (AdmissionService_ListSchoolsByOffsetClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AdmissionService_serviceDesc.Streams[3], "/unicampus.api.admission.v1.AdmissionService/ListSchoolsByOffset", opts...)
	if err != nil {
		return nil, err
	}
	x := &admissionServiceListSchoolsByOffsetClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AdmissionService_ListSchoolsByOffsetClient interface {
	Recv() (*School, error)
	grpc.ClientStream
}

type admissionServiceListSchoolsByOffsetClient struct {
	grpc.ClientStream
}

func (x *admissionServiceListSchoolsByOffsetClient) Recv() (*School, error) {
	m := new(School)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *admissionServiceClient) GetSchool(ctx context.Context, in *School, opts ...grpc.CallOption) (*School, error) {
	out := new(School)
	err := c.cc.Invoke(ctx, "/unicampus.api.admission.v1.AdmissionService/GetSchool", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *admissionServiceClient) PutSchool(ctx context.Context, in *School, opts ...grpc.CallOption) (*School, error) {
	out := new(School)
	err := c.cc.Invoke(ctx, "/unicampus.api.admission.v1.AdmissionService/PutSchool", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *admissionServiceClient) DeleteSchool(ctx context.Context, in *School, opts ...grpc.CallOption) (*School, error) {
	out := new(School)
	err := c.cc.Invoke(ctx, "/unicampus.api.admission.v1.AdmissionService/DeleteSchool", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *admissionServiceClient) AppyStudentToSchool(ctx context.Context, in *Application, opts ...grpc.CallOption) (*Application, error) {
	out := new(Application)
	err := c.cc.Invoke(ctx, "/unicampus.api.admission.v1.AdmissionService/AppyStudentToSchool", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *admissionServiceClient) GetStudent(ctx context.Context, in *Student, opts ...grpc.CallOption) (*Student, error) {
	out := new(Student)
	err := c.cc.Invoke(ctx, "/unicampus.api.admission.v1.AdmissionService/GetStudent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *admissionServiceClient) PutStudent(ctx context.Context, in *Student, opts ...grpc.CallOption) (*Student, error) {
	out := new(Student)
	err := c.cc.Invoke(ctx, "/unicampus.api.admission.v1.AdmissionService/PutStudent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *admissionServiceClient) DeleteStudent(ctx context.Context, in *Student, opts ...grpc.CallOption) (*Student, error) {
	out := new(Student)
	err := c.cc.Invoke(ctx, "/unicampus.api.admission.v1.AdmissionService/DeleteStudent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdmissionServiceServer is the server API for AdmissionService service.
type AdmissionServiceServer interface {
	ListSchools(AdmissionService_ListSchoolsServer) error
	ListSchoolsByQuery(*Query, AdmissionService_ListSchoolsByQueryServer) error
	ListSchoolsByCritera(*Critera, AdmissionService_ListSchoolsByCriteraServer) error
	ListSchoolsByOffset(*Offset, AdmissionService_ListSchoolsByOffsetServer) error
	GetSchool(context.Context, *School) (*School, error)
	PutSchool(context.Context, *School) (*School, error)
	DeleteSchool(context.Context, *School) (*School, error)
	AppyStudentToSchool(context.Context, *Application) (*Application, error)
	GetStudent(context.Context, *Student) (*Student, error)
	PutStudent(context.Context, *Student) (*Student, error)
	DeleteStudent(context.Context, *Student) (*Student, error)
}

func RegisterAdmissionServiceServer(s *grpc.Server, srv AdmissionServiceServer) {
	s.RegisterService(&_AdmissionService_serviceDesc, srv)
}

func _AdmissionService_ListSchools_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AdmissionServiceServer).ListSchools(&admissionServiceListSchoolsServer{stream})
}

type AdmissionService_ListSchoolsServer interface {
	Send(*School) error
	Recv() (*School, error)
	grpc.ServerStream
}

type admissionServiceListSchoolsServer struct {
	grpc.ServerStream
}

func (x *admissionServiceListSchoolsServer) Send(m *School) error {
	return x.ServerStream.SendMsg(m)
}

func (x *admissionServiceListSchoolsServer) Recv() (*School, error) {
	m := new(School)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _AdmissionService_ListSchoolsByQuery_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Query)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AdmissionServiceServer).ListSchoolsByQuery(m, &admissionServiceListSchoolsByQueryServer{stream})
}

type AdmissionService_ListSchoolsByQueryServer interface {
	Send(*School) error
	grpc.ServerStream
}

type admissionServiceListSchoolsByQueryServer struct {
	grpc.ServerStream
}

func (x *admissionServiceListSchoolsByQueryServer) Send(m *School) error {
	return x.ServerStream.SendMsg(m)
}

func _AdmissionService_ListSchoolsByCritera_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Critera)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AdmissionServiceServer).ListSchoolsByCritera(m, &admissionServiceListSchoolsByCriteraServer{stream})
}

type AdmissionService_ListSchoolsByCriteraServer interface {
	Send(*School) error
	grpc.ServerStream
}

type admissionServiceListSchoolsByCriteraServer struct {
	grpc.ServerStream
}

func (x *admissionServiceListSchoolsByCriteraServer) Send(m *School) error {
	return x.ServerStream.SendMsg(m)
}

func _AdmissionService_ListSchoolsByOffset_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Offset)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AdmissionServiceServer).ListSchoolsByOffset(m, &admissionServiceListSchoolsByOffsetServer{stream})
}

type AdmissionService_ListSchoolsByOffsetServer interface {
	Send(*School) error
	grpc.ServerStream
}

type admissionServiceListSchoolsByOffsetServer struct {
	grpc.ServerStream
}

func (x *admissionServiceListSchoolsByOffsetServer) Send(m *School) error {
	return x.ServerStream.SendMsg(m)
}

func _AdmissionService_GetSchool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(School)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdmissionServiceServer).GetSchool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/unicampus.api.admission.v1.AdmissionService/GetSchool",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdmissionServiceServer).GetSchool(ctx, req.(*School))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdmissionService_PutSchool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(School)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdmissionServiceServer).PutSchool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/unicampus.api.admission.v1.AdmissionService/PutSchool",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdmissionServiceServer).PutSchool(ctx, req.(*School))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdmissionService_DeleteSchool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(School)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdmissionServiceServer).DeleteSchool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/unicampus.api.admission.v1.AdmissionService/DeleteSchool",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdmissionServiceServer).DeleteSchool(ctx, req.(*School))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdmissionService_AppyStudentToSchool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Application)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdmissionServiceServer).AppyStudentToSchool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/unicampus.api.admission.v1.AdmissionService/AppyStudentToSchool",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdmissionServiceServer).AppyStudentToSchool(ctx, req.(*Application))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdmissionService_GetStudent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Student)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdmissionServiceServer).GetStudent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/unicampus.api.admission.v1.AdmissionService/GetStudent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdmissionServiceServer).GetStudent(ctx, req.(*Student))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdmissionService_PutStudent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Student)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdmissionServiceServer).PutStudent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/unicampus.api.admission.v1.AdmissionService/PutStudent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdmissionServiceServer).PutStudent(ctx, req.(*Student))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdmissionService_DeleteStudent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Student)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdmissionServiceServer).DeleteStudent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/unicampus.api.admission.v1.AdmissionService/DeleteStudent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdmissionServiceServer).DeleteStudent(ctx, req.(*Student))
	}
	return interceptor(ctx, in, info, handler)
}

var _AdmissionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "unicampus.api.admission.v1.AdmissionService",
	HandlerType: (*AdmissionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSchool",
			Handler:    _AdmissionService_GetSchool_Handler,
		},
		{
			MethodName: "PutSchool",
			Handler:    _AdmissionService_PutSchool_Handler,
		},
		{
			MethodName: "DeleteSchool",
			Handler:    _AdmissionService_DeleteSchool_Handler,
		},
		{
			MethodName: "AppyStudentToSchool",
			Handler:    _AdmissionService_AppyStudentToSchool_Handler,
		},
		{
			MethodName: "GetStudent",
			Handler:    _AdmissionService_GetStudent_Handler,
		},
		{
			MethodName: "PutStudent",
			Handler:    _AdmissionService_PutStudent_Handler,
		},
		{
			MethodName: "DeleteStudent",
			Handler:    _AdmissionService_DeleteStudent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListSchools",
			Handler:       _AdmissionService_ListSchools_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ListSchoolsByQuery",
			Handler:       _AdmissionService_ListSchoolsByQuery_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListSchoolsByCritera",
			Handler:       _AdmissionService_ListSchoolsByCritera_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListSchoolsByOffset",
			Handler:       _AdmissionService_ListSchoolsByOffset_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "generated.proto",
}

func (m *School) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *School) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Uuid) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintGenerated(dAtA, i, uint64(len(m.Uuid)))
		i += copy(dAtA[i:], m.Uuid)
	}
	if len(m.Name) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintGenerated(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	if len(m.Description) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintGenerated(dAtA, i, uint64(len(m.Description)))
		i += copy(dAtA[i:], m.Description)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *Student) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Student) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Uuid) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintGenerated(dAtA, i, uint64(len(m.Uuid)))
		i += copy(dAtA[i:], m.Uuid)
	}
	if len(m.FirstName) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintGenerated(dAtA, i, uint64(len(m.FirstName)))
		i += copy(dAtA[i:], m.FirstName)
	}
	if len(m.LastName) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintGenerated(dAtA, i, uint64(len(m.LastName)))
		i += copy(dAtA[i:], m.LastName)
	}
	if len(m.Description) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintGenerated(dAtA, i, uint64(len(m.Description)))
		i += copy(dAtA[i:], m.Description)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *Application) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Application) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Uuid) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintGenerated(dAtA, i, uint64(len(m.Uuid)))
		i += copy(dAtA[i:], m.Uuid)
	}
	if m.School != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintGenerated(dAtA, i, uint64(m.School.Size()))
		n1, err := m.School.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if m.Student != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintGenerated(dAtA, i, uint64(m.Student.Size()))
		n2, err := m.Student.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n2
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *Query) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Query) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Query) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintGenerated(dAtA, i, uint64(len(m.Query)))
		i += copy(dAtA[i:], m.Query)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *Critera) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Critera) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Sector) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintGenerated(dAtA, i, uint64(len(m.Sector)))
		i += copy(dAtA[i:], m.Sector)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *Offset) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Offset) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.First != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintGenerated(dAtA, i, uint64(m.First))
	}
	if m.Offset != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintGenerated(dAtA, i, uint64(m.Offset))
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func encodeVarintGenerated(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *School) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Uuid)
	if l > 0 {
		n += 1 + l + sovGenerated(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovGenerated(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovGenerated(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Student) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Uuid)
	if l > 0 {
		n += 1 + l + sovGenerated(uint64(l))
	}
	l = len(m.FirstName)
	if l > 0 {
		n += 1 + l + sovGenerated(uint64(l))
	}
	l = len(m.LastName)
	if l > 0 {
		n += 1 + l + sovGenerated(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovGenerated(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Application) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Uuid)
	if l > 0 {
		n += 1 + l + sovGenerated(uint64(l))
	}
	if m.School != nil {
		l = m.School.Size()
		n += 1 + l + sovGenerated(uint64(l))
	}
	if m.Student != nil {
		l = m.Student.Size()
		n += 1 + l + sovGenerated(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Query) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Query)
	if l > 0 {
		n += 1 + l + sovGenerated(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Critera) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sector)
	if l > 0 {
		n += 1 + l + sovGenerated(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Offset) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.First != 0 {
		n += 1 + sovGenerated(uint64(m.First))
	}
	if m.Offset != 0 {
		n += 1 + sovGenerated(uint64(m.Offset))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovGenerated(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozGenerated(x uint64) (n int) {
	return sovGenerated(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *School) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: School: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: School: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uuid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Uuid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Student) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Student: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Student: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uuid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Uuid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FirstName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FirstName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LastName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Application) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Application: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Application: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uuid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Uuid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field School", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.School == nil {
				m.School = &School{}
			}
			if err := m.School.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Student", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Student == nil {
				m.Student = &Student{}
			}
			if err := m.Student.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Query) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Query: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Query: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Query", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Query = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Critera) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Critera: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Critera: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sector", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sector = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Offset) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Offset: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Offset: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field First", wireType)
			}
			m.First = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.First |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Offset", wireType)
			}
			m.Offset = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Offset |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenerated(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthGenerated
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowGenerated
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipGenerated(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthGenerated = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenerated   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("generated.proto", fileDescriptor_generated_20fa2873433b475f) }

var fileDescriptor_generated_20fa2873433b475f = []byte{
	// 482 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0x4f, 0x6b, 0x13, 0x41,
	0x14, 0xef, 0x68, 0xba, 0x69, 0xde, 0x2a, 0x96, 0x69, 0x91, 0x10, 0x69, 0x68, 0xd7, 0x83, 0x3d,
	0x2d, 0x35, 0x82, 0x07, 0xc1, 0x43, 0xaa, 0xe0, 0x45, 0xaa, 0x6e, 0x14, 0x84, 0x1e, 0xca, 0xb8,
	0xfb, 0xa2, 0x03, 0xc9, 0xce, 0x3a, 0x33, 0x5b, 0x08, 0x7e, 0x11, 0x0f, 0xfd, 0x40, 0x1e, 0xfd,
	0x08, 0x12, 0xbf, 0x88, 0xcc, 0x9f, 0x40, 0x82, 0x71, 0x99, 0xc3, 0x7a, 0x9b, 0xf7, 0xe6, 0xf7,
	0xe7, 0xbd, 0xdf, 0x32, 0x09, 0xdc, 0xfb, 0x8c, 0x25, 0x4a, 0xa6, 0xb1, 0x48, 0x2b, 0x29, 0xb4,
	0xa0, 0x83, 0xba, 0xe4, 0x39, 0x9b, 0x57, 0xb5, 0x4a, 0x59, 0xc5, 0x53, 0x56, 0xcc, 0xb9, 0x52,
	0x5c, 0x94, 0xe9, 0xf5, 0xe3, 0x24, 0x83, 0x68, 0x92, 0x7f, 0x11, 0x62, 0x46, 0x29, 0x74, 0xea,
	0x9a, 0x17, 0x7d, 0x72, 0x4c, 0x4e, 0x7b, 0x99, 0x3d, 0x9b, 0x5e, 0xc9, 0xe6, 0xd8, 0xbf, 0xe5,
	0x7a, 0xe6, 0x4c, 0x8f, 0x21, 0x2e, 0x50, 0xe5, 0x92, 0x57, 0x9a, 0x8b, 0xb2, 0x7f, 0xdb, 0x5e,
	0xad, 0xb7, 0x92, 0x6f, 0xd0, 0x9d, 0xe8, 0xba, 0xc0, 0x52, 0x6f, 0x15, 0x3d, 0x02, 0x98, 0x72,
	0xa9, 0xf4, 0xd5, 0x9a, 0x74, 0xcf, 0x76, 0x2e, 0x8c, 0xfe, 0x03, 0xe8, 0xcd, 0xd8, 0xea, 0xd6,
	0xa9, 0xef, 0x99, 0xc6, 0xc5, 0x16, 0xf3, 0xce, 0xdf, 0xe6, 0x37, 0x04, 0xe2, 0x71, 0x55, 0xcd,
	0x78, 0xce, 0x4c, 0xbd, 0x75, 0x82, 0x67, 0x10, 0x29, 0xbb, 0xb4, 0x75, 0x8f, 0x47, 0x49, 0xfa,
	0xef, 0x84, 0x52, 0x17, 0x4f, 0xe6, 0x19, 0xf4, 0x39, 0x74, 0x95, 0x5b, 0xce, 0x0e, 0x17, 0x8f,
	0x1e, 0x36, 0x92, 0x1d, 0x34, 0x5b, 0x71, 0x92, 0x23, 0xd8, 0x7d, 0x57, 0xa3, 0x5c, 0xd0, 0x43,
	0xd8, 0xfd, 0x6a, 0x0e, 0x7e, 0x30, 0x57, 0x24, 0x27, 0xd0, 0x7d, 0x21, 0xb9, 0x46, 0xc9, 0xe8,
	0x7d, 0x88, 0x14, 0xe6, 0x5a, 0x48, 0x8f, 0xf0, 0x55, 0xf2, 0x14, 0xa2, 0x37, 0xd3, 0xa9, 0x42,
	0x6d, 0x24, 0x6c, 0x6c, 0x16, 0xd0, 0xc9, 0x5c, 0x61, 0x78, 0xc2, 0xde, 0xdb, 0xe5, 0x3a, 0x99,
	0xaf, 0x46, 0x37, 0x7b, 0xb0, 0x3f, 0x5e, 0xcd, 0x36, 0x41, 0x79, 0xcd, 0x73, 0xa4, 0x97, 0x10,
	0xbf, 0xe6, 0x4a, 0xbb, 0x1d, 0x15, 0x0d, 0x08, 0x62, 0x10, 0x80, 0x49, 0x76, 0x4e, 0xc9, 0x19,
	0xa1, 0x57, 0x40, 0xd7, 0xc4, 0xcf, 0x17, 0x6e, 0xf1, 0x93, 0x26, 0xbe, 0x85, 0x84, 0x59, 0x9c,
	0x11, 0x9a, 0xc3, 0xe1, 0x86, 0xc1, 0x2a, 0xba, 0xc6, 0x4f, 0xe2, 0x41, 0xc1, 0x26, 0x0c, 0x0e,
	0x36, 0x4c, 0x7c, 0xf8, 0x8d, 0x74, 0x87, 0x09, 0xb6, 0xf8, 0x00, 0xbd, 0x57, 0xe8, 0x1d, 0xda,
	0xfb, 0x06, 0x46, 0xf6, 0x6d, 0xdd, 0xbe, 0xec, 0x47, 0xb8, 0xf3, 0x12, 0x67, 0xa8, 0xb1, 0x75,
	0x65, 0x0e, 0x07, 0xe3, 0xaa, 0x5a, 0xf8, 0x47, 0xf3, 0x5e, 0x78, 0x83, 0x47, 0x4d, 0xe4, 0xb5,
	0xb7, 0x3e, 0x08, 0x05, 0xda, 0x25, 0xc0, 0x44, 0xee, 0x7f, 0xa6, 0x42, 0xde, 0xf0, 0x20, 0x04,
	0xe4, 0x94, 0x4d, 0xea, 0xff, 0x41, 0xf9, 0x12, 0xee, 0xfa, 0xe0, 0xdb, 0x17, 0x3f, 0xdf, 0xff,
	0xb1, 0x1c, 0x92, 0x9f, 0xcb, 0x21, 0xf9, 0xb5, 0x1c, 0x92, 0xef, 0xbf, 0x87, 0x3b, 0x9f, 0x22,
	0xfb, 0xef, 0xf1, 0xe4, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc8, 0x21, 0x8e, 0xaf, 0x50, 0x06,
	0x00, 0x00,
}
