// Code generated by protoc-gen-go. DO NOT EDIT.
// source: school.proto

package school

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type School struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *School) Reset()         { *m = School{} }
func (m *School) String() string { return proto.CompactTextString(m) }
func (*School) ProtoMessage()    {}
func (*School) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb068902851add0, []int{0}
}

func (m *School) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_School.Unmarshal(m, b)
}
func (m *School) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_School.Marshal(b, m, deterministic)
}
func (m *School) XXX_Merge(src proto.Message) {
	xxx_messageInfo_School.Merge(m, src)
}
func (m *School) XXX_Size() int {
	return xxx_messageInfo_School.Size(m)
}
func (m *School) XXX_DiscardUnknown() {
	xxx_messageInfo_School.DiscardUnknown(m)
}

var xxx_messageInfo_School proto.InternalMessageInfo

func (m *School) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *School) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type SearchSchoolByQueryRequest struct {
	Query                string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchSchoolByQueryRequest) Reset()         { *m = SearchSchoolByQueryRequest{} }
func (m *SearchSchoolByQueryRequest) String() string { return proto.CompactTextString(m) }
func (*SearchSchoolByQueryRequest) ProtoMessage()    {}
func (*SearchSchoolByQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb068902851add0, []int{1}
}

func (m *SearchSchoolByQueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchSchoolByQueryRequest.Unmarshal(m, b)
}
func (m *SearchSchoolByQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchSchoolByQueryRequest.Marshal(b, m, deterministic)
}
func (m *SearchSchoolByQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchSchoolByQueryRequest.Merge(m, src)
}
func (m *SearchSchoolByQueryRequest) XXX_Size() int {
	return xxx_messageInfo_SearchSchoolByQueryRequest.Size(m)
}
func (m *SearchSchoolByQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchSchoolByQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchSchoolByQueryRequest proto.InternalMessageInfo

func (m *SearchSchoolByQueryRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type SearchSchoolByQueryReply struct {
	Schools              []*School `protobuf:"bytes,1,rep,name=schools,proto3" json:"schools,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SearchSchoolByQueryReply) Reset()         { *m = SearchSchoolByQueryReply{} }
func (m *SearchSchoolByQueryReply) String() string { return proto.CompactTextString(m) }
func (*SearchSchoolByQueryReply) ProtoMessage()    {}
func (*SearchSchoolByQueryReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb068902851add0, []int{2}
}

func (m *SearchSchoolByQueryReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchSchoolByQueryReply.Unmarshal(m, b)
}
func (m *SearchSchoolByQueryReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchSchoolByQueryReply.Marshal(b, m, deterministic)
}
func (m *SearchSchoolByQueryReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchSchoolByQueryReply.Merge(m, src)
}
func (m *SearchSchoolByQueryReply) XXX_Size() int {
	return xxx_messageInfo_SearchSchoolByQueryReply.Size(m)
}
func (m *SearchSchoolByQueryReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchSchoolByQueryReply.DiscardUnknown(m)
}

var xxx_messageInfo_SearchSchoolByQueryReply proto.InternalMessageInfo

func (m *SearchSchoolByQueryReply) GetSchools() []*School {
	if m != nil {
		return m.Schools
	}
	return nil
}

type SearchSchoolByCriteraRequest struct {
	Sector               string   `protobuf:"bytes,1,opt,name=sector,proto3" json:"sector,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchSchoolByCriteraRequest) Reset()         { *m = SearchSchoolByCriteraRequest{} }
func (m *SearchSchoolByCriteraRequest) String() string { return proto.CompactTextString(m) }
func (*SearchSchoolByCriteraRequest) ProtoMessage()    {}
func (*SearchSchoolByCriteraRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb068902851add0, []int{3}
}

func (m *SearchSchoolByCriteraRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchSchoolByCriteraRequest.Unmarshal(m, b)
}
func (m *SearchSchoolByCriteraRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchSchoolByCriteraRequest.Marshal(b, m, deterministic)
}
func (m *SearchSchoolByCriteraRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchSchoolByCriteraRequest.Merge(m, src)
}
func (m *SearchSchoolByCriteraRequest) XXX_Size() int {
	return xxx_messageInfo_SearchSchoolByCriteraRequest.Size(m)
}
func (m *SearchSchoolByCriteraRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchSchoolByCriteraRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchSchoolByCriteraRequest proto.InternalMessageInfo

func (m *SearchSchoolByCriteraRequest) GetSector() string {
	if m != nil {
		return m.Sector
	}
	return ""
}

type SearchSchoolByCriteraReply struct {
	Schools              []*School `protobuf:"bytes,1,rep,name=schools,proto3" json:"schools,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SearchSchoolByCriteraReply) Reset()         { *m = SearchSchoolByCriteraReply{} }
func (m *SearchSchoolByCriteraReply) String() string { return proto.CompactTextString(m) }
func (*SearchSchoolByCriteraReply) ProtoMessage()    {}
func (*SearchSchoolByCriteraReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb068902851add0, []int{4}
}

func (m *SearchSchoolByCriteraReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchSchoolByCriteraReply.Unmarshal(m, b)
}
func (m *SearchSchoolByCriteraReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchSchoolByCriteraReply.Marshal(b, m, deterministic)
}
func (m *SearchSchoolByCriteraReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchSchoolByCriteraReply.Merge(m, src)
}
func (m *SearchSchoolByCriteraReply) XXX_Size() int {
	return xxx_messageInfo_SearchSchoolByCriteraReply.Size(m)
}
func (m *SearchSchoolByCriteraReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchSchoolByCriteraReply.DiscardUnknown(m)
}

var xxx_messageInfo_SearchSchoolByCriteraReply proto.InternalMessageInfo

func (m *SearchSchoolByCriteraReply) GetSchools() []*School {
	if m != nil {
		return m.Schools
	}
	return nil
}

type ListSchoolRequest struct {
	First                uint64   `protobuf:"varint,1,opt,name=first,proto3" json:"first,omitempty"`
	Offset               uint64   `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSchoolRequest) Reset()         { *m = ListSchoolRequest{} }
func (m *ListSchoolRequest) String() string { return proto.CompactTextString(m) }
func (*ListSchoolRequest) ProtoMessage()    {}
func (*ListSchoolRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb068902851add0, []int{5}
}

func (m *ListSchoolRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSchoolRequest.Unmarshal(m, b)
}
func (m *ListSchoolRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSchoolRequest.Marshal(b, m, deterministic)
}
func (m *ListSchoolRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSchoolRequest.Merge(m, src)
}
func (m *ListSchoolRequest) XXX_Size() int {
	return xxx_messageInfo_ListSchoolRequest.Size(m)
}
func (m *ListSchoolRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSchoolRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListSchoolRequest proto.InternalMessageInfo

func (m *ListSchoolRequest) GetFirst() uint64 {
	if m != nil {
		return m.First
	}
	return 0
}

func (m *ListSchoolRequest) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type ListSchoolReply struct {
	Schools              []*School `protobuf:"bytes,1,rep,name=schools,proto3" json:"schools,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListSchoolReply) Reset()         { *m = ListSchoolReply{} }
func (m *ListSchoolReply) String() string { return proto.CompactTextString(m) }
func (*ListSchoolReply) ProtoMessage()    {}
func (*ListSchoolReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb068902851add0, []int{6}
}

func (m *ListSchoolReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSchoolReply.Unmarshal(m, b)
}
func (m *ListSchoolReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSchoolReply.Marshal(b, m, deterministic)
}
func (m *ListSchoolReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSchoolReply.Merge(m, src)
}
func (m *ListSchoolReply) XXX_Size() int {
	return xxx_messageInfo_ListSchoolReply.Size(m)
}
func (m *ListSchoolReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSchoolReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListSchoolReply proto.InternalMessageInfo

func (m *ListSchoolReply) GetSchools() []*School {
	if m != nil {
		return m.Schools
	}
	return nil
}

type GetSchoolRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSchoolRequest) Reset()         { *m = GetSchoolRequest{} }
func (m *GetSchoolRequest) String() string { return proto.CompactTextString(m) }
func (*GetSchoolRequest) ProtoMessage()    {}
func (*GetSchoolRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb068902851add0, []int{7}
}

func (m *GetSchoolRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSchoolRequest.Unmarshal(m, b)
}
func (m *GetSchoolRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSchoolRequest.Marshal(b, m, deterministic)
}
func (m *GetSchoolRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSchoolRequest.Merge(m, src)
}
func (m *GetSchoolRequest) XXX_Size() int {
	return xxx_messageInfo_GetSchoolRequest.Size(m)
}
func (m *GetSchoolRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSchoolRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSchoolRequest proto.InternalMessageInfo

func (m *GetSchoolRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetSchoolReply struct {
	School               *School  `protobuf:"bytes,1,opt,name=school,proto3" json:"school,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSchoolReply) Reset()         { *m = GetSchoolReply{} }
func (m *GetSchoolReply) String() string { return proto.CompactTextString(m) }
func (*GetSchoolReply) ProtoMessage()    {}
func (*GetSchoolReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb068902851add0, []int{8}
}

func (m *GetSchoolReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSchoolReply.Unmarshal(m, b)
}
func (m *GetSchoolReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSchoolReply.Marshal(b, m, deterministic)
}
func (m *GetSchoolReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSchoolReply.Merge(m, src)
}
func (m *GetSchoolReply) XXX_Size() int {
	return xxx_messageInfo_GetSchoolReply.Size(m)
}
func (m *GetSchoolReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSchoolReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetSchoolReply proto.InternalMessageInfo

func (m *GetSchoolReply) GetSchool() *School {
	if m != nil {
		return m.School
	}
	return nil
}

func init() {
	proto.RegisterType((*School)(nil), "school.School")
	proto.RegisterType((*SearchSchoolByQueryRequest)(nil), "school.SearchSchoolByQueryRequest")
	proto.RegisterType((*SearchSchoolByQueryReply)(nil), "school.SearchSchoolByQueryReply")
	proto.RegisterType((*SearchSchoolByCriteraRequest)(nil), "school.SearchSchoolByCriteraRequest")
	proto.RegisterType((*SearchSchoolByCriteraReply)(nil), "school.SearchSchoolByCriteraReply")
	proto.RegisterType((*ListSchoolRequest)(nil), "school.ListSchoolRequest")
	proto.RegisterType((*ListSchoolReply)(nil), "school.ListSchoolReply")
	proto.RegisterType((*GetSchoolRequest)(nil), "school.GetSchoolRequest")
	proto.RegisterType((*GetSchoolReply)(nil), "school.GetSchoolReply")
}

func init() { proto.RegisterFile("school.proto", fileDescriptor_fdb068902851add0) }

var fileDescriptor_fdb068902851add0 = []byte{
	// 357 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x4f, 0x4f, 0xfa, 0x40,
	0x10, 0xfd, 0xd1, 0x1f, 0xd6, 0x30, 0x28, 0xea, 0xa8, 0x58, 0x1b, 0x0f, 0xcd, 0xc6, 0x18, 0x4e,
	0x1c, 0x30, 0x31, 0x26, 0x26, 0x1a, 0xd1, 0xe8, 0xc5, 0x8b, 0xe5, 0xec, 0x01, 0xcb, 0x10, 0x36,
	0x41, 0xb6, 0xec, 0x2e, 0x26, 0xfd, 0xa6, 0x7e, 0x1c, 0xc3, 0xee, 0x96, 0xbf, 0x55, 0xc3, 0x6d,
	0xdf, 0xce, 0x9b, 0xf7, 0x66, 0xe7, 0xb5, 0xb0, 0xa3, 0x92, 0x81, 0x10, 0xc3, 0x66, 0x2a, 0x85,
	0x16, 0xe8, 0x5b, 0xc4, 0x6e, 0xc1, 0xef, 0x98, 0x13, 0x22, 0x94, 0x47, 0xdd, 0x0f, 0x0a, 0x4a,
	0x51, 0xa9, 0x51, 0x89, 0xcd, 0x19, 0x23, 0xa8, 0xf6, 0x48, 0x25, 0x92, 0xa7, 0x9a, 0x8b, 0x51,
	0xe0, 0x99, 0xd2, 0xe2, 0x15, 0x6b, 0x41, 0xd8, 0xa1, 0xae, 0x4c, 0x06, 0x56, 0xa5, 0x9d, 0xbd,
	0x4e, 0x48, 0x66, 0x31, 0x8d, 0x27, 0xa4, 0x34, 0x1e, 0xc1, 0xd6, 0x78, 0x8a, 0x9d, 0xa8, 0x05,
	0xec, 0x11, 0x82, 0xc2, 0x9e, 0x74, 0x98, 0x61, 0x03, 0xb6, 0xed, 0x64, 0x2a, 0x28, 0x45, 0xff,
	0x1b, 0xd5, 0x56, 0xad, 0xe9, 0xe6, 0xb6, 0xe4, 0x38, 0x2f, 0xb3, 0x2b, 0x38, 0x5b, 0x56, 0x79,
	0x90, 0x5c, 0x93, 0xec, 0xe6, 0xde, 0x75, 0xf0, 0x15, 0x25, 0x5a, 0x48, 0x67, 0xee, 0x10, 0x7b,
	0x5a, 0x9d, 0x78, 0xd6, 0xb7, 0x99, 0xff, 0x3d, 0x1c, 0xbc, 0x70, 0xa5, 0xdd, 0xf5, 0xfc, 0xc1,
	0x7d, 0x2e, 0x95, 0x36, 0x9e, 0xe5, 0xd8, 0x82, 0xe9, 0x28, 0xa2, 0xdf, 0x57, 0xa4, 0xcd, 0x06,
	0xcb, 0xb1, 0x43, 0xec, 0x06, 0xf6, 0x16, 0x25, 0x36, 0xf3, 0x67, 0xb0, 0xff, 0x4c, 0x2b, 0xf6,
	0x35, 0xf0, 0x78, 0xcf, 0xbd, 0xd7, 0xe3, 0x3d, 0x76, 0x0d, 0xb5, 0x05, 0xce, 0x54, 0xff, 0x02,
	0x5c, 0xf2, 0x86, 0xb5, 0x2e, 0xef, 0xaa, 0xad, 0x2f, 0x0f, 0x76, 0xed, 0x55, 0x87, 0xe4, 0x27,
	0x4f, 0x08, 0xdf, 0xe0, 0xb0, 0x20, 0x35, 0x64, 0x33, 0x81, 0x1f, 0x3f, 0x83, 0x30, 0xfa, 0x95,
	0x93, 0x0e, 0x33, 0xf6, 0x0f, 0x13, 0x38, 0x2e, 0x8c, 0x05, 0xcf, 0x8b, 0x9b, 0x97, 0xd3, 0x0e,
	0xd9, 0x1f, 0x2c, 0x6b, 0xd2, 0x06, 0x98, 0x2f, 0x1c, 0x4f, 0xf3, 0x9e, 0xb5, 0x1c, 0xc3, 0x93,
	0xa2, 0x92, 0xd5, 0xb8, 0x83, 0xca, 0x6c, 0xa7, 0x18, 0xe4, 0xbc, 0xd5, 0x28, 0xc2, 0x7a, 0x41,
	0xc5, 0x08, 0xbc, 0xfb, 0xe6, 0x0f, 0xbc, 0xfc, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xb8, 0x90, 0xe5,
	0xc0, 0x91, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SchoolServiceClient is the client API for SchoolService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SchoolServiceClient interface {
	SearchSchoolByQuery(ctx context.Context, in *SearchSchoolByQueryRequest, opts ...grpc.CallOption) (*SearchSchoolByQueryReply, error)
	SearchSchoolByCritera(ctx context.Context, in *SearchSchoolByCriteraRequest, opts ...grpc.CallOption) (*SearchSchoolByCriteraReply, error)
	ListSchool(ctx context.Context, in *ListSchoolRequest, opts ...grpc.CallOption) (*ListSchoolReply, error)
	GetSchool(ctx context.Context, in *GetSchoolRequest, opts ...grpc.CallOption) (*GetSchoolReply, error)
}

type schoolServiceClient struct {
	cc *grpc.ClientConn
}

func NewSchoolServiceClient(cc *grpc.ClientConn) SchoolServiceClient {
	return &schoolServiceClient{cc}
}

func (c *schoolServiceClient) SearchSchoolByQuery(ctx context.Context, in *SearchSchoolByQueryRequest, opts ...grpc.CallOption) (*SearchSchoolByQueryReply, error) {
	out := new(SearchSchoolByQueryReply)
	err := c.cc.Invoke(ctx, "/school.SchoolService/SearchSchoolByQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schoolServiceClient) SearchSchoolByCritera(ctx context.Context, in *SearchSchoolByCriteraRequest, opts ...grpc.CallOption) (*SearchSchoolByCriteraReply, error) {
	out := new(SearchSchoolByCriteraReply)
	err := c.cc.Invoke(ctx, "/school.SchoolService/SearchSchoolByCritera", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schoolServiceClient) ListSchool(ctx context.Context, in *ListSchoolRequest, opts ...grpc.CallOption) (*ListSchoolReply, error) {
	out := new(ListSchoolReply)
	err := c.cc.Invoke(ctx, "/school.SchoolService/ListSchool", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schoolServiceClient) GetSchool(ctx context.Context, in *GetSchoolRequest, opts ...grpc.CallOption) (*GetSchoolReply, error) {
	out := new(GetSchoolReply)
	err := c.cc.Invoke(ctx, "/school.SchoolService/GetSchool", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SchoolServiceServer is the server API for SchoolService service.
type SchoolServiceServer interface {
	SearchSchoolByQuery(context.Context, *SearchSchoolByQueryRequest) (*SearchSchoolByQueryReply, error)
	SearchSchoolByCritera(context.Context, *SearchSchoolByCriteraRequest) (*SearchSchoolByCriteraReply, error)
	ListSchool(context.Context, *ListSchoolRequest) (*ListSchoolReply, error)
	GetSchool(context.Context, *GetSchoolRequest) (*GetSchoolReply, error)
}

func RegisterSchoolServiceServer(s *grpc.Server, srv SchoolServiceServer) {
	s.RegisterService(&_SchoolService_serviceDesc, srv)
}

func _SchoolService_SearchSchoolByQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchSchoolByQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolServiceServer).SearchSchoolByQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/school.SchoolService/SearchSchoolByQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolServiceServer).SearchSchoolByQuery(ctx, req.(*SearchSchoolByQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchoolService_SearchSchoolByCritera_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchSchoolByCriteraRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolServiceServer).SearchSchoolByCritera(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/school.SchoolService/SearchSchoolByCritera",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolServiceServer).SearchSchoolByCritera(ctx, req.(*SearchSchoolByCriteraRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchoolService_ListSchool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSchoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolServiceServer).ListSchool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/school.SchoolService/ListSchool",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolServiceServer).ListSchool(ctx, req.(*ListSchoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchoolService_GetSchool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSchoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolServiceServer).GetSchool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/school.SchoolService/GetSchool",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolServiceServer).GetSchool(ctx, req.(*GetSchoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SchoolService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "school.SchoolService",
	HandlerType: (*SchoolServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchSchoolByQuery",
			Handler:    _SchoolService_SearchSchoolByQuery_Handler,
		},
		{
			MethodName: "SearchSchoolByCritera",
			Handler:    _SchoolService_SearchSchoolByCritera_Handler,
		},
		{
			MethodName: "ListSchool",
			Handler:    _SchoolService_ListSchool_Handler,
		},
		{
			MethodName: "GetSchool",
			Handler:    _SchoolService_GetSchool_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "school.proto",
}
